apiVersion: v1
kind: Namespace
metadata:
  name: simple-api
---
apiVersion: v1
kind: Service
metadata:
  name: simple-api-svc
spec:
  selector:
    app: simple-api
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-api
spec:
  selector:
    matchLabels:
      app: simple-api
  template:
    metadata:
      labels:
        app: simple-api
    spec:
      containers:
      - name: simple-api
        image: vietvite/simple-api:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
#argo test
